export type FlowerCategory = "classic" | "romantic" | "wild";

export interface FlowerCard {
  id: string;
  koreanName: string;
  scientificName: string;
  category: FlowerCategory;
  meaning: string;
  keywords: string[];
  season: "봄" | "여름" | "가을" | "겨울" | "사계";
  accent: string;
  image: string;
}

export const FLOWERS: FlowerCard[] = [
  {
    id: "01",
    koreanName: "동백꽃",
    scientificName: "Camellia japonica",
    category: "classic",
    meaning: "진심을 오래 지키는 사랑",
    keywords: ["진심", "기다림", "단단한 마음"],
    season: "겨울",
    accent: "ring-red-600/40",
    image: "/flowers/01.png",
  },
  {
    id: "02",
    koreanName: "진달래",
    scientificName: "Rhododendron mucronulatum",
    category: "classic",
    meaning: "조심스럽게 피어나는 시작",
    keywords: ["설렘", "그리움", "봄의 시작"],
    season: "봄",
    accent: "ring-pink-500/40",
    image: "/flowers/02.png",
  },
  {
    id: "03",
    koreanName: "매화",
    scientificName: "Prunus mume",
    category: "classic",
    meaning: "고요한 인내",
    keywords: ["인내", "품격", "차분함"],
    season: "겨울",
    accent: "ring-rose-300/40",
    image: "/flowers/03.png",
  },
  {
    id: "04",
    koreanName: "무궁화",
    scientificName: "Hibiscus syriacus",
    category: "classic",
    meaning: "다시 일어나는 힘",
    keywords: ["회복", "끈기", "존재감"],
    season: "여름",
    accent: "ring-fuchsia-400/40",
    image: "/flowers/04.png",
  },
  {
    id: "05",
    koreanName: "연꽃",
    scientificName: "Nelumbo nucifera",
    category: "classic",
    meaning: "흔들림 속에서도 맑아지는 마음",
    keywords: ["정화", "평정", "내면의 힘"],
    season: "여름",
    accent: "ring-rose-300/40",
    image: "/flowers/05.png",
  },
  {
    id: "06",
    koreanName: "국화",
    scientificName: "Chrysanthemum morifolium",
    category: "classic",
    meaning: "성숙한 마음",
    keywords: ["결실", "여유", "오래가는 빛"],
    season: "가을",
    accent: "ring-amber-400/40",
    image: "/flowers/06.png",
  },
  {
    id: "07",
    koreanName: "도라지꽃",
    scientificName: "Platycodon grandiflorus",
    category: "classic",
    meaning: "변하지 않는 약속",
    keywords: ["신뢰", "기다림", "오래된 마음"],
    season: "여름",
    accent: "ring-violet-400/40",
    image: "/flowers/07.png",
  },
  {
    id: "08",
    koreanName: "코스모스",
    scientificName: "Cosmos bipinnatus",
    category: "classic",
    meaning: "가볍지만 흔들리지 않는 순정",
    keywords: ["순수", "균형", "가을바람"],
    season: "가을",
    accent: "ring-pink-400/40",
    image: "/flowers/08.png",
  },
  {
    id: "09",
    koreanName: "봉선화",
    scientificName: "Impatiens balsamina",
    category: "classic",
    meaning: "건드리면 번지는 마음",
    keywords: ["기억", "첫 마음", "어린 감정"],
    season: "여름",
    accent: "ring-rose-500/40",
    image: "/flowers/09.png",
  },
  {
    id: "10",
    koreanName: "철쭉",
    scientificName: "Rhododendron schlippenbachii",
    category: "classic",
    meaning: "한때를 환하게 물들이는 기쁨",
    keywords: ["활기", "변화", "따뜻한 관계"],
    season: "봄",
    accent: "ring-pink-300/40",
    image: "/flowers/10.png",
  },
  {
    id: "11",
    koreanName: "붉은 장미",
    scientificName: "Rosa hybrida",
    category: "romantic",
    meaning: "숨기기 어려운 열정",
    keywords: ["사랑", "용기", "표현"],
    season: "사계",
    accent: "ring-red-500/40",
    image: "/flowers/11.png",
  },
  {
    id: "12",
    koreanName: "튤립",
    scientificName: "Tulipa gesneriana",
    category: "romantic",
    meaning: "말보다 먼저 피어나는 고백",
    keywords: ["고백", "기대", "선명한 마음"],
    season: "봄",
    accent: "ring-rose-400/40",
    image: "/flowers/12.png",
  },
  {
    id: "13",
    koreanName: "해바라기",
    scientificName: "Helianthus annuus",
    category: "romantic",
    meaning: "한 방향을 향하는 믿음",
    keywords: ["집중", "응원", "긍정"],
    season: "여름",
    accent: "ring-yellow-400/40",
    image: "/flowers/13.png",
  },
  {
    id: "14",
    koreanName: "제비꽃",
    scientificName: "Viola mandshurica",
    category: "romantic",
    meaning: "조용하지만 깊은 애정",
    keywords: ["겸손", "다정함", "작은 용기"],
    season: "봄",
    accent: "ring-violet-500/40",
    image: "/flowers/14.png",
  },
  {
    id: "15",
    koreanName: "라벤더",
    scientificName: "Lavandula angustifolia",
    category: "romantic",
    meaning: "마음을 가라앉히는 평온",
    keywords: ["휴식", "치유", "편안함"],
    season: "여름",
    accent: "ring-purple-400/40",
    image: "/flowers/15.png",
  },
  {
    id: "16",
    koreanName: "분홍 카네이션",
    scientificName: "Dianthus caryophyllus",
    category: "romantic",
    meaning: "고마움을 잊지 않는 마음",
    keywords: ["감사", "보살핌", "따뜻함"],
    season: "봄",
    accent: "ring-pink-400/40",
    image: "/flowers/16.png",
  },
  {
    id: "17",
    koreanName: "물망초",
    scientificName: "Myosotis scorpioides",
    category: "romantic",
    meaning: "잊히지 않는 약속",
    keywords: ["기억", "약속", "소중함"],
    season: "봄",
    accent: "ring-sky-400/40",
    image: "/flowers/17.png",
  },
  {
    id: "18",
    koreanName: "아이리스",
    scientificName: "Iris sanguinea",
    category: "romantic",
    meaning: "좋은 소식이 다가오는 문",
    keywords: ["소식", "희망", "우아함"],
    season: "봄",
    accent: "ring-indigo-400/40",
    image: "/flowers/18.png",
  },
  {
    id: "19",
    koreanName: "클레마티스",
    scientificName: "Clematis florida",
    category: "wild",
    meaning: "상상력이 길을 여는 순간",
    keywords: ["상상", "도약", "새 관점"],
    season: "여름",
    accent: "ring-violet-300/40",
    image: "/flowers/19.png",
  },
  {
    id: "20",
    koreanName: "에델바이스",
    scientificName: "Leontopodium nivale",
    category: "wild",
    meaning: "쉽게 흔들리지 않는 순수함",
    keywords: ["순수", "용기", "높은 기준"],
    season: "겨울",
    accent: "ring-stone-300/40",
    image: "/flowers/20.png",
  },
  {
    id: "21",
    koreanName: "헤더",
    scientificName: "Calluna vulgaris",
    category: "wild",
    meaning: "고요히 버티는 행운",
    keywords: ["행운", "보호", "담담함"],
    season: "가을",
    accent: "ring-fuchsia-300/40",
    image: "/flowers/21.png",
  },
  {
    id: "22",
    koreanName: "쌍둥이꽃",
    scientificName: "Linnaea borealis",
    category: "wild",
    meaning: "서로를 비추는 인연",
    keywords: ["연결", "동행", "공감"],
    season: "여름",
    accent: "ring-rose-200/40",
    image: "/flowers/22.png",
  },
  {
    id: "23",
    koreanName: "은방울꽃",
    scientificName: "Convallaria majalis",
    category: "wild",
    meaning: "다시 찾아오는 기쁨",
    keywords: ["회복", "기쁨", "작은 축복"],
    season: "봄",
    accent: "ring-emerald-200/40",
    image: "/flowers/23.png",
  },
  {
    id: "24",
    koreanName: "마거리트",
    scientificName: "Argyranthemum frutescens",
    category: "wild",
    meaning: "솔직한 질문이 여는 답",
    keywords: ["솔직함", "선택", "가벼운 확신"],
    season: "사계",
    accent: "ring-yellow-200/40",
    image: "/flowers/24.png",
  },
];

export const FLOWERS_BY_ID = new Map(FLOWERS.map((flower) => [flower.id, flower]));
